name: 'multi-input'
description: 'No description'

inputs:
  path:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -xe

        echo '${{ inputs.path }}'

        echo '${{ inputs.path }}' | hexdump -c

