on:
  workflow_dispatch:
    inputs:
      spec_failure:
        default: false
        type: boolean
      test_android_failure:
        default: false
        type: boolean
      build_android_failure:
        default: false
        type: boolean
      test_windows_failure:
        default: false
        type: boolean
      build_windows_failure:
        default: false
        type: boolean
      packaging_failure:
        default: false
        type: boolean
      upload_failure:
        default: false
        type: boolean
      notify_slack:
        default: false
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"

  spec:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - run: echo "TEST"
      - if: ${{ fromJson(inputs.spec_failure) }}
        run: exit 1

  test_ios:
    runs-on: ubuntu-latest
    needs: [spec]
    steps:
      - run: echo "TEST"

  build_ios:
    needs: [test_ios]
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"

  test_android:
    runs-on: ubuntu-latest
    needs: [spec]
    steps:
      - run: echo "TEST"
      - if: ${{ fromJson(inputs.test_android_failure) }}
        run: exit 1

  build_android:
    needs: [test_android]
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"
      - if: ${{ fromJson(inputs.build_android_failure) }}
        run: exit 1

  test_windows:
    needs: [spec]
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"
      - if: ${{ fromJson(inputs.test_windows_failure) }}
        run: exit 1

  build_windows:
    runs-on: ubuntu-latest
    needs: [test_windows]
    steps:
      - run: echo "TEST"
      - if: ${{ fromJson(inputs.build_windows_failure) }}
        run: exit 1

  packaging:
    needs: [build_ios, build_android, build_windows]
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"
      - if: ${{ fromJson(inputs.packaging_failure) }}
        run: exit 1

  upload:
    needs: [packaging]
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"
      - if: ${{ fromJson(inputs.upload_failure) }}
        run: exit 1

  notify_slack:
    needs: [upload]
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"
      - if: ${{ fromJson(inputs.notify_slack_failure) }}
        run: exit 1

