on:
  push:

jobs:
  google-cloud-storage-test:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - id: 'auth'
      #   uses: 'google-github-actions/auth@v1'
      #   with:
      #     credentials_json: '${{ secrets.GCP_CREDENTIAL }}'

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v0.2.0

      # - id: 'upload-file'
      #   uses: 'google-github-actions/upload-cloud-storage@v1'
      #   with:
      #     path: '/path/to/file'
      #     destination: 'bucket-name/file'

      # - run: echo "TEST"

      # - run: |
      #     gcloud info
      #     gcloud storage ls || true
      #     gcloud storage ls gs://gh-self-hosted-runner-test/


      # - id: 'upload-files'
      #   uses: 'google-github-actions/upload-cloud-storage@v1'
      #   with:
      #     path: 'app/'
      #     destination: 'gh-self-hosted-runner-test/runs/${{ github.run_id }}'
      #     glob: '**/*.rb'

      - name: Cache unity Library directory
        uses: mansagroup/gcs-cache-action@main
        with:
          bucket: gh-self-hosted-runner-test
          path: '*'
          key: cache-test-${{ github.sha }}
          restore-keys: |
            cache-test-

